import 'package:flutter/material.dart';
import 'app_theme_extension.dart';

/// Color values identical to the current `AppColors` static class —
/// this is the "no visual change" baseline. Existing (unmigrated) widgets
/// keep reading `AppColors.xxx` directly; migrated widgets reading
/// `context.colors.xxx` under `appLightTheme` see the exact same values.
const AppThemeColors lightColors = AppThemeColors(
  primary: Color(0xFF0041C8),
  primaryContainer: Color(0xFF0055FF),
  onPrimary: Color(0xFFFFFFFF),
  secondary: Color(0xFF505F76),
  onSecondary: Color(0xFFFFFFFF),
  background: Color(0xFFFAF8FF),
  backgroundSideBar: Color(0xFF283044),
  sideBarItems: Color(0xFFDCE1FF),
  sideBarItemsActive: Color(0xFFFFFFFF),
  sideBarBackgroundActive: Color(0xFF38485D),
  surface: Color(0xFFFFFFFF),
  surfaceDim: Color(0xFFD2D9F4),
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerLow: Color(0xFFF2F3FF),
  surfaceContainer: Color(0xFFEAEDFF),
  surfaceContainerHigh: Color(0xFFE2E7FF),
  surfaceContainerHighest: Color(0xFFDAE2FD),
  textPrimary: Color(0xFF131B2E),
  textSecondary: Color(0xFF434656),
  border: Color(0xFFE2E8F0),
  outline: Color(0xFF737688),
  outlineVariant: Color(0xFFC3C5D9),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  success: Color(0xFF047857),
  successContainer: Color(0xFFD0F2E6),
  warning: Color(0xFFF59E0B),
  warningContainer: Color(0xFFFEF3C7),
  info: Color(0xFF0284C7),
  infoContainer: Color(0xFFE0F2FE),
  primaryDark: Color(0xFF0039B3),
  primaryLight: Color(0xFF60A5FA),
  secondaryDark: Color(0xFF0B1C30),
  onPrimaryFixed: Color(0xFF001551),
  primaryFixedDim: Color(0xFFB6C4FF),
  onSecondaryContainer: Color(0xFF54647A),
  surfaceBright: Color(0xFFFAF8FF),
  surfaceVariant: Color(0xFFDAE2FD),
  onSurface: Color(0xFF131B2E),
  onSurfaceVariant: Color(0xFF434656),
  onBackground: Color(0xFF131B2E),
  onErrorContainer: Color(0xFF93000A),
  inverseSurface: Color(0xFF283044),
  inverseOnSurface: Color(0xFFEEF0FF),
  inversePrimary: Color(0xFFB6C4FF),
  successGreen: Color(0xFF1A6B3C),
  secondaryContainer: Color(0xFFD0E1FB),
  onPrimaryContainer: Color(0xFFE3E6FF),
  primaryFixed: Color(0xFFDCE1FF),
  onPrimaryFixedVariant: Color(0xFF0039B3),
  statusHealthyBg: Color(0xFFECFDF5),
  statusHealthyFg: Color(0xFF065F46),
  statusHealthyBorder: Color(0xFFD1FAE5),
  statusHealthyDot: Color(0xFF059669),
  statusPendingBg: Color(0xFFFFFBEB),
  statusPendingFg: Color(0xFFB45309),
  statusPendingBorder: Color(0xFFFDE68A),
  statusPendingDot: Color(0xFFD97706),
  statusCancelledBg: Color(0xFFFFDAD6),
  statusCancelledFg: Color(0xFF93000A),
  statusCancelledBorder: Color(0xFFFFB4AB),
  statusCancelledDot: Color(0xFFBA1A1A),
  posPrimaryDark: Color(0xFF0039B3),
  posSurface: Color(0xFFF7F8FC),
  posBorder: Color(0xFFE5E8F2),
  posTextPrimary: Color(0xFF131B2E),
  posTextSecondary: Color(0xFF6B7280),
  posSuccess: Color(0xFF22C55E),
  posError: Color(0xFFBA1A1A),
  posSidebarBg: Color(0xFF131B2E),
  posSidebarBgLight: Color(0xFF1B2438),
  posSidebarActive: Color(0xFF22304F),
  posPrimary: Color(0xFF0041C8),
  posCardBg: Color(0xFFFFFFFF),
  posCartBg: Color(0xFFFAFAFE),
  posSummaryBg: Color(0xFFE9ECFB),
  posTextMuted: Color(0xFF9CA3AF),
  tertiary: Color(0xFF4B5053),
  onSuccessContainer: Color(0xFF15803D),
  onWarningContainer: Color(0xFFC2410C),
  neutralContainer: Color(0xFFF1F5F9),
  onNeutralContainer: Color(0xFF64748B),
  cardBorder: Color(0xFFE2E8F0),
  cardHoverBorder: Color(0xFFC3C9E6),
  cardNested: Color(0xFFF2F3FF),
  dialogSurface: Color(0xFFFFFFFF),
  dialogScrim: Color(0x66131B2E),
  menuSurface: Color(0xFFFFFFFF),
  tableHeaderBg: Color(0xFFF6F7FE),
  tableRowHover: Color(0xFFEFF1FF),
  tableRowSelected: Color(0xFFE3E6FF),
  tableBorder: Color(0xFFE9ECF6),
  sidebarHoverBg: Color(0xFF34435C),
  sidebarDivider: Color(0xFF3A4A61),
  sidebarActiveIndicator: Color(0xFF7DA6FF),
  inputBg: Color(0xFFFFFFFF),
  inputBorder: Color(0xFFC3C5D9),
  inputFocusBorder: Color(0xFF0041C8),
  focusRing: Color(0x660041C8),
  scrollbarThumb: Color(0xFFC3C5D9),
  dividerSubtle: Color(0xFFEDEFF7),
);

ThemeData buildAppLightTheme() {
  return ThemeData(
    brightness: Brightness.light,
    colorScheme: ColorScheme.fromSeed(
      seedColor: lightColors.primary,
      primary: lightColors.primary,
      brightness: Brightness.light,
    ),
    scaffoldBackgroundColor: lightColors.background,
    useMaterial3: true,
    extensions: const [lightColors],
  );
}