name: management_inventory_pro
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.8
  get_it: ^9.2.1
  supabase_flutter: ^2.14.1
  window_manager: ^0.5.1
  flutter_svg: ^2.3.0
  flutter_gen_runner: ^5.14.1
  flutter_gen: ^5.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.15.0


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/


flutter_gen:
  output: lib/generated/
  line_length: 80

